version: '3.1'

services:

  mongo:
    image: mongo:3
    restart: always
    ports:
      - 27017:27017
    volumes:
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=bia